### ISSUE TITLE
neovim crash when `git commit`

### ISSUE THREAD

**Issue by pedro757** [lukas-reineke/cmp-rg#16]
`stack traceback:                                                                                                                                                                                             
^I[C]: in function 'json_decode'                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:29: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 Vim:E474: Unexpected end of input: {"type
":"context","data":{"path":{"text":"./Desktop/kube/images/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/ProgressIndicator.php"},"lines":{"text":"     */\n"},"line_number":100,"absolute_offset
":`

There are a lot more of this messages but everyone shows an error in **json_decode** in line **29** of the **init.lua**

I think if there is no workspace it fails because in a normal project it works

How to reproduce this error:
1. `git config core.editor nvim`
2. `git commit`

**Comment by lukas-reineke** [comment]
It is a `json_decode` error. Something ripgrep returns as json can't be parsed by Neovim.
Can you post the whole error message? I'll add a check to the json decode, but I would like to know what ripgrep returned.

**Comment by lukas-reineke** [comment]
this is the same issue as #15 
I will close this issue, but if you can share the whole error message, please post it on that issue.

**Comment by pedro757** [comment]
> Can you post the whole error message? I'll add a check to the json decode, but I would like to know what ripgrep returned.

It's a huge message, how can pass the whole message?

**Comment by lukas-reineke** [comment]
I think it's fine then, you don't need to post it.
Can you test #17 and see if that fixes it?

**Comment by pedro757** [comment]
Now it shows this:

^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25>                                                               
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25>
