### ISSUE TITLE
error when `git commit`

### ISSUE THREAD

**Issue by pedro757** [lukas-reineke/cmp-rg#21]
I get this running `:messages`

stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:34: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:34: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:62: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:62: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:62: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:62: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:34: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:34: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:34: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:62: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25>                                                               
...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: attempt to index field 'text' (a nil value)                                                                                                  
stack traceback:                                                                                                                                                                                             
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:62: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
ua/cmp-rg/init.lua:62: attempt to index field 'text' (a nil value)                                                                                                                                           
stack traceback:

**Comment by pedro757** [comment]
This line:

https://github.com/lukas-reineke/cmp-rg/blob/6009869f62551022bd78b47d5b53eb96036acf69/lua/cmp-rg/init.lua#L34

and this:

https://github.com/lukas-reineke/cmp-rg/blob/6009869f62551022bd78b47d5b53eb96036acf69/lua/cmp-rg/init.lua#L62

**Comment by lukas-reineke** [comment]
Thanks, should be fixed now

**Comment by pedro757** [comment]
Yep, thank you.
