### ISSUE TITLE
How to exclude certain files to be searched?

### ISSUE THREAD

**Issue by nyngwang** [lukas-reineke/cmp-rg#33]
As title. it causes seriously lagging when the the current working directory contains multiple projects where each has a `node_modules/` folder.

**Comment by lukas-reineke** [comment]
ripgrep should not search in directories that are ignored by git.
If you want to track them with git, but ignore them from ripgrep, you can make a `.rgignore`

You can read the ripgrep documentation for more information

https://github.com/BurntSushi/ripgrep/blob/df83b8b44426b3f2179abe632eb183e8c8270524/doc/rg.1.txt.tpl#L113
