### ISSUE TITLE
Feature request: grep only active buffer extension 

### ISSUE THREAD

**Issue by amerov** [lukas-reineke/cmp-rg#36]
example:
e: `user.rb`
on completion run rg only for `rb` extension files

**Comment by lukas-reineke** [comment]
That's pretty difficult to do with ripgrep, and cmp-buffer can already cover this

https://github.com/hrsh7th/cmp-buffer#all-buffers

**Comment by xzbdmw** [comment]
Doesn't rg have a --type flag for this usage?
