### ISSUE TITLE
[Perf] Using this source in very large projects causes noticeable input lag

### ISSUE THREAD

**Issue by akinsho** [lukas-reineke/cmp-rg#42]
I've recently discovered this plugin and have been trying it on my work repository, unfortunately I find that it unfortunately blocks input slightly on keypress. It's not completely blocked, but the input delay is noticeably higher if typing fast.

I tried limiting the recursive depth search and considered only allowing it to search files in the same folder as the current buffer but in the case of the depth this didn't seem to work and by limiting searching to something like 2 when I'm already like 6 levels deep I don't get useful suggestions.

On the other hand, I looked at setting the root to use but couldn't find a way to set it to my current buffer's direct parent directory i.e. should it be a function, so I can dynamically return a root to use or...

Is there some way to improve the performance of the source generally when searching quite large repositories. Generally ripgrep has always seemed to perform quite quickly for me and I have it set it to ignore things like node modules already, but I've never used it on a per keystroke level, so hard to know if this is a limit of that tool or an issue of this plugin.

**Comment by lukas-reineke** [comment]
The `ripgrep` process is using jobs, that shouldn't be the problem. I suspect you just get a lot of results and parsing them is slow. Have you tried setting `keyword_length` to 3-5? I find lower than that, you don't get relevant suggestions anyway.

Accepting a function for the directory would be pretty easy. If the keyword length doesn't fix it, I can add that.

**Comment by lukas-reineke** [comment]
> sometimes selecting the first item (I use no preselect) blocks neovim.

I can't reproduce this :thinking:
I tried it in the Linux repo, the `ripgrep` results take a second to populate, but it never blocks. They just get added to the completion list. Selecting also doesn't block.

**Comment by lukas-reineke** [comment]
After a bit of more investigation, I managed to reproduce, and I also found the issue.

ripgrep supports streaming results, so `cmp-rg` also calls `cmp` every time there are new results, instead of once at the end. But it seems like `cmp` re-processes all items when there are new results (which makes sense). When ripgrep finds a lot of results, this is actually called _a lot_. Like for every ~5 results, then `cmp` needs to process all items again. If there are 1000 items, this is slow :sweat_smile: 

I'll add chuncking to reduce the number of times `cmp` needs to re-process.

**Comment by lukas-reineke** [comment]
I made a PR, can you check if that fixes it?

**Comment by akinsho** [comment]
Awesome, thanks for investigating 👍🏿, I'll give the branch a go today and feedback

**Comment by akinsho** [comment]
Seems to be working really well, haven't a single once of the blocking episodes all day today
