### ISSUE TITLE
Limit the total amount of results

### ISSUE THREAD

**Issue by daver32** [lukas-reineke/cmp-rg#49]
Hello,

it would be nice if there was a way to configure a hard limit on the amount of results returned. I think it would be the most versatile option for performance tuning. There are multiple params that rg accepts to set limits, but they all have their drawbacks.

It seems that the only way to achieve this is to terminate rg after it has returned the max amount of results. I can make a PR if that's welcome.

**Comment by lukas-reineke** [comment]
It's a good point, does #50 work for you?
